Given /^there is not an unconfirmed user with sha1_salt "([^"]*)"$/ do |key|
  User.destroy_all(:sha1_salt => key)
end

Given /^there is an unconfirmed user with sha1_salt "([^"]*)" and email "([^"]*)"$/ do |sha1_salt, email|
    user = User.create!(
      :name => "default name",
      :email => email,
      :username => "default username",
      :password => "default password",
      :password_confirmation => "default password",
      :sha1_salt => sha1_salt);
    key = ConfirmationKey.create!( :key => User.encrypt(email, sha1_salt) )
    key.user = user
    key.save
end

When /^I confirm the key "([^"]*)"$/ do |key|
  visit "/confirm?key=#{key}"
end

When /^I confirm the key generated by sha1_salt "([^"]*)" and email "([^"]*)"$/ do |sha1_salt, email|
  key = User.encrypt(email, sha1_salt)
  visit "/confirm?key=#{key}"
end

