Given /^there is not an unconfirmed user with password_salt "([^"]*)"$/ do |key|
  User.destroy_all(:password_salt => key)
end

Given /^there is an unconfirmed user with password_salt "([^"]*)" and email "([^"]*)"$/ do |password_salt, email|
    User.create!(
      :name => "default name",
      :email => email,
      :username => "default username",
      :password => "default password",
      :password_confirmation => "default password",
      :password_salt => password_salt);
end

When /^I confirm the key "([^"]*)"$/ do |key|
  visit "/confirm?key=#{key}"
end

When /^I confirm the key generated by password_salt "([^"]*)" and email "([^"]*)"$/ do |password_salt, email|
  key = User.encrypt(email, password_salt)
  visit "/confirm?key=#{key}"
end

